# Generated by Django 4.2.5 on 2023-12-17 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2)),
                ('update', models.DateTimeField(default=datetime.datetime(2023, 12, 17, 11, 29, 18, 384161))),
            ],
        ),
    ]
