# Generated by Django 4.2.5 on 2023-12-26 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 10, 43, 168849)),
        ),
    ]
