# Generated by Django 4.2.5 on 2023-12-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_information_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
        migrations.AddField(
            model_name='location_pic',
            name='description',
            field=models.CharField(default='暂无', max_length=4096),
        ),
    ]
