# Generated by Django 4.2.5 on 2023-12-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_information_image_location_pic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('description', models.CharField(default='暂无', max_length=4096)),
            ],
        ),
    ]
