# Generated by Django 4.2.5 on 2023-12-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_feature',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='city_feature',
            name='city_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
