# Generated by Django 4.2.5 on 2023-12-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_feature',
            name='description',
            field=models.TextField(default='暂无', max_length=4096),
        ),
        migrations.AlterField(
            model_name='location_pic',
            name='description',
            field=models.TextField(default='暂无', max_length=4096),
        ),
    ]
